### PR TITLE
Fix import error due to #71

### LINKED ISSUE #74: Error after updating to 5.0.0
After updating to verision 5.0.0 I get the following error, in multiple different codebases

```rust
error[E0463]: can't find crate for `rust_embed_utils`
  --> src/main.rs:59:10
   |
59 | #[derive(RustEmbed)]
   |          ^^^^^^^^^ can't find crate
```

The error is fixed by adding the following to `Cargo.toml` so it seems like something is missing a dependency.
```
rust-embed-utils = "5.0.0"
```

rustc 1.36.0 (a53f9df32 2019-07-03)
cargo 1.36.0 (c4fcfb725 2019-05-15)

### PR DESCRIPTION
**Pull request by Mcat12**
The utils crate is re-exported from the main crate for use in debug builds.

Debug builds are compiled by the macro to use certain functions from the utils crate. This is different than in release mode, where the macro itself uses the functions and does not require them at runtime. When the debug code tries to import the utils crate, it fails because it is not an explicit dependency in Cargo.toml.

Fixes #74

### CODE REVIEW

**Comment by pyros2097** [comment]
Hah.. `as utils;` thats what i was missing. LGTM. Thanks @Mcat12
