### ISSUE TITLE
Error after updating to 5.0.0

### ISSUE THREAD

**Issue by rushsteve1** [pyros2097/rust-embed#74]
After updating to verision 5.0.0 I get the following error, in multiple different codebases

```rust
error[E0463]: can't find crate for `rust_embed_utils`
  --> src/main.rs:59:10
   |
59 | #[derive(RustEmbed)]
   |          ^^^^^^^^^ can't find crate
```

The error is fixed by adding the following to `Cargo.toml` so it seems like something is missing a dependency.
```
rust-embed-utils = "5.0.0"
```

rustc 1.36.0 (a53f9df32 2019-07-03)
cargo 1.36.0 (c4fcfb725 2019-05-15)

**Comment by Mcat12** [comment]
@pyros2097 I also see this on my project. We should probably re-export the utils crate in the main crate, then use it that way.

**Comment by Mcat12** [comment]
However, surprisingly my Dependabot PR didn't fail the build? https://github.com/pi-hole/api/pull/190

**Comment by rushsteve1** [comment]
My Dependabot PR **did** fail with both `5.0.0` and `5.0.1`.

**Comment by pyros2097** [comment]
I wonder how the tests are passing then. This is such a weird case. I almost thought I published the crate without adding the `rust_embed_utils` as a dependency

**Comment by pyros2097** [comment]
I'm lost with this one. I tried adding it to the lib.rs or rust-embed and still no luck. the release builds are working though. Don't know why just the debug builds are breaking.

**Comment by rushsteve1** [comment]
Here is an isolated example that you can get to compile in some ways.
[embedtest.zip](https://github.com/pyros2097/rust-embed/files/3374285/embedtest.zip)

**Comment by Mcat12** [comment]
Ah, that's probably the difference. My CI compiles in release mode, whereas @rushsteve1's CI probably compiles it in debug mode at some point.
